### PR TITLE
Ensure the switch toggle is stacked on-top of the switch icons.

### PR DESCRIPTION
**Pull request by dbatiste**
This is required specifically for RTL.

Before fix (RTL):
localhost_8000_components_switch_demo_switch html (1)

After fix (RTL):
localhost_8000_components_switch_demo_switch html

### CODE REVIEW

**Comment by dbatiste** [comment]
Seems we have a couple really flakey tests.  I will probably merge this as-is, unless I can sort out the reason for the flake.  Ran CI 3 times and got different set of errors with this in both BrowserStack and Sauce.

**Review by svanherk — APPROVED** [review]
Should we have a visual-diff test for this?

**Comment by dbatiste** [comment]
> Should we have a visual-diff test for this?

Haha good question - we actually have RTL tests for this, but for some strange reason, our visual-diff RTL setup doesn't capture this bug.  I will look at an alternate way to apply dir in the test that might capture it.

**Review by svanherk — APPROVED** [review]
Looks good!

**Pull request merged**
