### PR TITLE
Remove extra whitespace hiding inside d2l-link elements

### PR DESCRIPTION
**Pull request by j3parker**
This gap was really noticable when a link was beside punctuation (e.g. commas, periods, ...)

I noticed this when [switching the blog to use Brightspace UI](https://github.com/Brightspace/cdo-blog/pull/179). Here's the before:

image

and after:

image

(re-opening #302 which was from a fork and couldn't run all of CI)

### CODE REVIEW

**Comment by j3parker** [comment]
So the [d2l-link](https://s3.ca-central-1.amazonaws.com/visualdiff.gaudi.d2l/screenshots/BrightspaceUI/core/link/2019-12-09-14.58.41.250-4b8a1227ce90c6a38efaacd191e8ae8f2780c260-report.html) "difference" (no golden) is expected, and I'm guessing I'm supposed to click the link to regenerate goldens from the branch?

But the one for [d2l-dialog-mixin](https://s3.ca-central-1.amazonaws.com/visualdiff.gaudi.d2l/screenshots/BrightspaceUI/core/dialog-mixin/2019-12-09-14.57.41.14-4b8a1227ce90c6a38efaacd191e8ae8f2780c260-report.html) I don't understand.

**Comment by dlockhart** [comment]
Hmm yeah could be a weird timing problem with that test (@dbatiste FYI [results here](https://s3.ca-central-1.amazonaws.com/visualdiff.gaudi.d2l/screenshots/BrightspaceUI/core/dialog-mixin/2019-12-09-14.57.41.14-4b8a1227ce90c6a38efaacd191e8ae8f2780c260-report.html) ) -- I've re-run the build so hopefully it doesn't happen twice.

**Comment by j3parker** [comment]
SHould I make the d2l-link test a span rather than p so it doesn't have so much whitespace in the golden?

**Comment by dlockhart** [comment]
Sure yeah that would be good!

**Pull request merged**
