### PR TITLE
Revert "[DE52324] Update CSS to allow _focusing attribute to be elevated to a…"

### PR DESCRIPTION
**Pull request by jesseag**
Reverts BrightspaceUI/core#3426

Reverting these changes as per Mango's standup discussion as they end up creating a very undesirable/unusable experience in Firefox.

### CODE REVIEW

**Comment by jesseag** [comment]
I see that there has been a Vdiff change but for some reason I am not able to pull it into my branch via the Github UI? I guess I can merge it in manually. Also, VDiff status checks just seem to be hanging. Not sure why though as everything looks to be fine on the Github Status page right now.

**Comment by dbatiste** [comment]
> I see that there has been a Vdiff change but for some reason in the `main` branch I am not able to pull it into my branch via the Github UI? I guess I can merge it in manually.

That particular test is flakey. I'd rerun the diffs until it works. I think @svanherk is trying to make a couple of these tests less flakey at the moment.

**Comment by jesseag** [comment]
> > I see that there has been a Vdiff change but for some reason in the `main` branch I am not able to pull it into my branch via the Github UI? I guess I can merge it in manually.
> 
> That particular test is flakey. I'd rerun the diffs until it works. I think @svanherk is trying to make a couple of these tests less flakey at the moment.

Sounds good. Will do!

**Comment by eKoopmans** [comment]
Yep in fact if you merge or rebase onto main, you'll get a fix that should remove the entire flakiness of that particular visual-diff 🤞.

And yes the "merge main branch" option in the GitHub UI is something that's configurable per-repo, we don't have it turned on here - you'll have to do that locally and push it up.

**Comment by jesseag** [comment]
> Yep in fact if you merge or rebase onto main, you'll get a fix that should remove the entire flakiness of that particular visual-diff 🤞.
> 
> And yes the "merge main branch" option in the GitHub UI is something that's configurable per-repo, we don't have it turned on here - you'll have to do that locally and push it up.

Sounds good. Thanks what I figured. Will do. Thanks Eric.

**Review by eKoopmans — APPROVED** [review]

**Review by dbatiste — APPROVED** [review]

**Comment by jesseag** [comment]
Should I add anything into my merged commit message to ensure that this gets a patch release? It is not a fix so I figured `:fix` probably doesn't make sense. I can also just merge it and wait till it gets picked up in the next patch release.

**Comment by eKoopmans** [comment]
Yep I'd recommend squash-merging and adding the `fix: ` prefix to the commit message at that stage to trigger the release. I'd say this counts as a fix.

**Comment by jesseag** [comment]
> Yep I'd recommend squash-merging and adding the `fix: ` prefix to the commit message at that stage to trigger the release. I'd say this counts as a fix.

Done thanks!

**Pull request merged**
