### PR TITLE
Updating Translations 1909 8/29/2019

### PR DESCRIPTION
**Pull request by BrightspaceGitHubReader**

### CODE REVIEW

**Comment by dlockhart** [comment]
@m6jones probably worth getting your 👀 on this one!

**Comment by dlockhart** [comment]
Looks like these are going into the wrong directory... they should be going into `components/meter/lang/`.

**Comment by m6jones** [comment]
This looks like an issue with me not pointing to the correct file. I can merge this and skip versioning and then ill put up a new PR with a fixed config and putting the files in the right folder.

**Comment by dlockhart** [comment]
Sounds good. FYI, it's set up to skip versioning by default, so no need to explicitly skip.

**Comment by m6jones** [comment]
You will have to approve the PR before I can merge.

**Pull request merged**
