### PR TITLE
DE43686-fix-overlap-click-conflict

### PR DESCRIPTION
**Pull request by KaiPrince**
## Overview

 Before | After 
------- | ------
 image | image 

Resolves a stacking conflict where clicks would activate the item below.

### Reason for change

See ticket: [DE43686](https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F605803449744&view=aea56dea-ee73-4c07-9842-cc15d4efc0ea&fdp=true?fdp=true): 2. WTD Full view Back to Home link disabled if another link under it

### Changes summarized

- Add `z-index: 0` to create new stacking context.

### Suggested future tasks

* Migration of nav components to core.
* Warning: This may affect drag and drop functionality. Regression tests may be required.

## Checklist

- [x] No new warnings are introduced
- [x] Comments and documentation are up to date
- [x] TODOs resolved or added to issue tracker
- [x] No commented-out code
- [x] This isn't a 'quick-and-dirty' job

### CODE REVIEW

**Comment by KaiPrince** [comment]
This replaces https://github.com/BrightspaceUI/navigation/pull/115.

**Comment by KaiPrince** [comment]
Oh man. Tests are failing. Will investigate further.

**Comment by svanherk** [comment]
```
  form-element
    events
      ✖ should fire invalid-change when validation fails
```

^ That Sauce Labs test is very flakey and unlikely to be related to your stuff.  You don't need the Sauce Labs tests to pass to merge (we're investigating Browserstack versus Sauce, but only Browserstack is _required_ to pass).

**Comment by dbatiste** [comment]
I think this change would be ok.

**Comment by KaiPrince** [comment]
Why is this still in draft?

Because the tests are failing and I think it might be because of my changes.

**Review by svanherk — APPROVED** [review]
@KaiPrince I pulled in `main` since there was some improvements to the flakey test you were seeing

**Comment by KaiPrince** [comment]
@svanherk Many thanks!

**Pull request merged**
