### PR TITLE
Use safer replace API to support older browsers

### PR DESCRIPTION
**Pull request by grant-cleary**
Backport of this PR: https://github.com/BrightspaceUI/core/pull/2458

It has been decided to pull this back into 20.22.5/20.22.4 because it's a safe change that might help clear up error logs and make diagnosing other issues much easier.

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]

**Comment by grant-cleary** [comment]
It... Looks like the visual diff tests are running against the new version of puppeteer on this older branch, so there are like a billion updated goldens to merge. Is it fine if I do?

**Comment by grant-cleary** [comment]
I sampled a subset of the diff reports and they're all the minor visual changes I would expect from bumping Chrome. I just merged in the new goldens.

**Comment by grant-cleary** [comment]
I'm an idiot. I've been re-running these visual diff tests because they look wrong, but it's because one of the new dialog goldens I merged in earlier had a flaky failure.

**Comment by dlockhart** [comment]
Yeah it's OK to merge these changes in.

**Comment by grant-cleary** [comment]
I mean at this rate I'm not sure I'm ever going to get the tests green at all, so we'll see how that goes.

**Pull request merged**
