### PR TITLE
Date filter/list: Radio button: consistency between space and click [GAUD-6576]

### PR DESCRIPTION
**Pull request by margaree**
Part of [Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6576)

**Problem:**
In list, the radio buttons toggle on click but not on space.

**Expected Behaviour:**
Generally radio buttons are not able to be de-selected once selected. However, I did discuss this with Jeff and he felt that since UX best practice is to allow a user to be able to undo their changes easily that the consistent behaviour here should be to be able to de-select on subsequent click/space. This change might be controversial so let me know any opinions here.

**Solution Notes:**
I put this behind a property, `radioToggle`, in order to not affect existing usages of `SelectionMixin` and required opt-in (though this can create inconsistency in our system so let me know thoughts on this). I then opted in for list. I also didn't document this in case we want to hide it at this point.

### CODE REVIEW

**Review by dbatiste — COMMENTED** [review]
> This change might be controversial so let me know any opinions here. 

Yeah, I have mixed feelings about it because it deviates from native radio behaviour, and in doing so, might be confusing to users. But without this, there would need to be some other way for the user to indicate "no selection", such as consumers providing a "None" option, or a button to clear the selection. Having said that, I know this isn't exactly like a standard group of radios in a form - there could be a couple subtle differences in how this is announced already. 🤷‍♂️ 

> I put this behind a property, radioToggle, in order to not affect existing usages of SelectionMixin and required opt-in (though this can create inconsistency in our system so let me know thoughts on this). I then opted in for list. I also didn't document this in case we want to hide it at this point.

Ideally we only surface this option if we need to. Should the user always have the ability to deselect? Might we have consumers that assume there will always be a selection? I think we only have a few usages of `selection-single`, so we could converse with Jeff about them. Maybe we really do need this to be opt-in, or maybe we really don't want it to be a consumer choice.  Thoughts @geurts?

If we do need opt-in, maybe it should be `allow-deselect`, `allow-unselect`, or `selection-single-deselect`, etc... a property that describes the behaviour it provides. The selection components also render checkboxes depending on the `selection-single` property, so whatever name we choose should jive with that. Thoughts?

**Comment by geurts** [comment]
@dbatiste I agree that we don't want this to be opt-in unless there's a strong need. Can we find the few existing instances of single-selection lists to validate? I'm fairly certain this will not be disruptive to them but would be good to confirm.

In the future, if the need arises to prevent de-selection, then we can worry about an opt in property at that time right?

To your other question: I feel allowing deselection of single-selection list items is a good thing, despite the visual and semantic use of radio inputs that don't support it natively. I believe the reason native radios don't allow this is because they're designed to be used with a default option, which would be selected initially and could be selected later to effectively "deslect" or undo your selection. But **a)** many usages on the web don't offer a default option and instead start with all radios in an unselected state; once the user selects an option, they cannot return to an unselected state, which you could argue is a flaw in the native input behaviour (though it's arguably not a usage they were originally designed to support). And **b)** our usage in a list item context doesn't typically come with an equivalent of the default option, so I think it makes sense to diverge from native behaviour to allow users to deselect (which we've already done for click/pointer users, just not for hitting Space).

**Comment by dbatiste** [comment]
> I agree that we don't want this to be opt-in unless there's a strong need. Can we find the few existing instances of single-selection lists to validate? I'm fairly certain this will not be disruptive to them but would be good to confirm.

Sounds like that's what we should do.

> In the future, if the need arises to prevent de-selection, then we can worry about an opt in property at that time right?

Yep, sounds good to me.

Re rationale... yeah, there's been decades of debate and criticism about this. While there are solutions that use native elements as-is, I understand and agree that they aren't great. I wish I there was something better. Lots of people have suggested mutually exclusive checkboxes to solve this, and hacking checkboxes has been (rightfully) met with just as much (if not more) criticism as overriding native radio behaviour.

**Comment by margaree** [comment]
I audited all the usages found [here](https://search.d2l.dev/search?project=Brightspace&project=BrightspaceHypermediaComponents&project=BrightspaceUI&project=BrightspaceUILabs&project=lms&full=%22selection-single%22&defs=&refs=&path=js&hist=&type=&xrd=&nn=5&si=path&si=path&n=25). There was 1 case ([here](https://search.d2l.dev/xref/Brightspace/ipsis-sis-course-merge/components/start-time-filter.js?r=8a9c3ad0#53)) that stood out as assuming that if their `selection-single` filter was de-selected then `cleared` would be `true`, which is currently not the case. We could either go into this usage and update the code to account for that, or we could set `cleared` to true when the `selection-single` radio option is de-selected within filter.

**Pull request merged**
