### PR TITLE
Fix linear-meter margins

### PR DESCRIPTION
**Pull request by bearfriend**
@m6jones FYI, this is what I _think_ the margins should be (at least for our use-case). Feel free to approve this, use it as a template, or close it.

### CODE REVIEW

**Comment by m6jones** [comment]
Before you merge actually, would you be able to change the margin and height values to `rem` units.

**Comment by dlockhart** [comment]
Should we have been expecting the perceptual diff tests to need updating?

**Comment by m6jones** [comment]
Yes, we will need to regenerate the golden and the screenshots for the readme.

**Comment by dbatiste** [comment]
I think it skipped the visual-diff and ran the headless unit tests (as opposed to running Sauce since there are not secure keys (coming from a fork).

**Comment by bearfriend** [comment]
What can I/we do to get this merged?

**Comment by m6jones** [comment]
I made a draft PR from a branch https://github.com/BrightspaceUI/core/pull/115
This will let us run the tests and make some goldens.

**Pull request closed without merging**
