### PR TITLE
Option 2 - custom-style processor

### PR DESCRIPTION
**Pull request by dbatiste**
Defines a custom style processor that will wait for `DOMContentLoaded`, look for `<style class="d2l-custom-style">`, and then process them with the shadyCSS processor.  Not sure if there could be timing issues.  The nice thing about this approach (in contrast to Option 1) is that the consumer can place their styles in a vanilla `style` element, directly in the `head` where we typically expect place them.

### CODE REVIEW

**Comment by dlockhart** [comment]
I share your concern here around timing, and also that it only ever runs once. If for some reason things get lazy loaded in later, it wouldn't know to re-run. That may not be a concern if we can assume those things are always Lit/Polymer elements though.

I do like that it's just a regular `<style>` element though -- a lot. The weirdness with custom elements not being allowed in the `<head>` is super gross and will cause all kinds of bugs. Not if you you're able to see if this approach causes the style to be processed twice? Like once by the browser initially and then again when the call to `ShadyCSS.CustomStyleInterface.addCustomStyle(style)` happens? I'm not sure what that's doing under the covers, but presumably it's modifying the CSS and then re-adding it to the `<head>`?

**Comment by dbatiste** [comment]
Yeah this doesn't work super well if we load styles lazily.  We may not need that now, but it would be unfortunate if we did in the future and our solution did not work.

For IE11 it appears to replace the stylesheet, either with a new element or by rewriting the contents.  The shadyCSS rewrites selectors and variables.  The browser probably processes it twice, but I'm not certain.  For other browsers, it probably just leaves them alone.

**Comment by dlockhart** [comment]
Gotcha. So depending on timing, the original `<style>` might get parsed and a paint might happen... then it could get replaced and re-parsed and another paint. Probably not a big deal unless there were a lot of these on the page.

**Comment by dbatiste** [comment]
Closing since we will defer creating something to support document level overrides until more cases come up.

**Pull request closed without merging**
