### PR TITLE
Add no-header option for d2l-dialog-fullscreen.

### PR DESCRIPTION
**Pull request by dbatiste**

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]
Haha weird seeing a dialog with no header... not much of a dialog anymore!

**Comment by dbatiste** [comment]
> Haha weird seeing a dialog with no header... not much of a dialog anymore!

Yeah I think they have some ideas to make further changes though - no be not quite so fullscreen.  Still in flux though.

image

**Comment by dlockhart** [comment]
@dbatiste is this work still needed?

**Comment by dbatiste** [comment]
> @dbatiste is this work still needed?
 
I think we can close this.

**Pull request closed without merging**
