### PR TITLE
User Profile: Convert to lit mixin

### PR DESCRIPTION
**Pull request by margaree**
I put this in `components` for now but perhaps we want some more organization with that? (e.g., `hm-components`).

This was mostly copy pasted from `user-profile-behavior`, pretty much worked as is, with the addition of an example consumer element for demoing/to make sure it worked. I also created `helpers-hm` and added `d2l-organization-hm-behavior` to that.

### CODE REVIEW

**Comment by svanherk** [comment]
I'm probably confused, but it looks like this is not https://github.com/BrightspaceHypermediaComponents/users/tree/master/components?

**Comment by margaree** [comment]
This is https://github.com/Brightspace/user-profile-behavior. Was `d2l-profile-image` the expected conversion?

**Comment by svanherk** [comment]
I was under the impression we were thinking of converting https://github.com/BrightspaceHypermediaComponents/users/blob/master/components/d2l-profile-image-base.js (UI) and seeing if that still worked in https://github.com/BrightspaceHypermediaComponents/users/blob/master/components/d2l-profile-image.js (HM), and then converting the HM one to test that, but I may have old info.  We've probably tested this all out now anyways, with the Lit + Polymer thing with subtle-button and icons, and HM now with this PR

**Comment by margaree** [comment]
Interesting, I must have missed that, sorry for the confusion! I can take a look at those conversions as well just to make sure. You're right though - based on what's been done so far I would expect it to be fine.

**Comment by dlockhart** [comment]
I was thinking the same as Stacey -- that we'd attempt the component Miles built. Sorry for the confusion Margaree!

**Comment by svanherk** [comment]
Yeah, I'm also not sure what goes in this core repo... I think way back when we were thinking we'd own generic HM helpers, but not components.  Maya's working on Entity classes that would understand a certain HM route and live in the corresponding repo.  We may want a `core` repo in https://github.com/BrightspaceHypermediaComponents to hold the HM stuff we own.

But what about that https://github.com/BrightspaceHypermediaComponents/users/blob/master/components/d2l-profile-image-base.js component?  It was originally in BrightspaceUI, then moved to the HM `users` repo.  I kinda think that one should move back in here... we have all the core UI components that have a design on `design.d2l` that we could take back into the monolith, whether they are HM or not

**Comment by dbatiste** [comment]
I think I am leaning towards those HM components living elsewhere still.  I think testing all the "core" core elements will be a lot already.  I could be convinced otherwise though.  I definitely would like a clear distinction between those types of components.

**Comment by dlockhart** [comment]
Yeah, I'm leaning that way too Dave. We want the benefits of a monorepo (things that depend heavily on each other build together) without introducing the drawbacks (slow build times, hard to break stuff out). @margaree, would it make sense to just try to upgrade that component to Lit as a non-merging pull request in its existing repo? Then we can pull that into BSI and test it out.

**Comment by margaree** [comment]
@dlockhart yup that should work.

**Pull request closed without merging**
